<?php

namespace BeerToBeer\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BeerRepository extends EntityRepository
{
	public function getAllBeersArray() {
		$query = $this->_em->createQuery('
			SELECT be
			FROM BeerToBeerCoreBundle:Beer be
			')
		;

		return $query->getArrayResult();
	}
}
