<?php

namespace BeerToBeer\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessRepository extends EntityRepository
{
	/**
	 * getClosestBusinesses($latitude, $longitude, $offset = 0, $limit = 10)
	 *
	 * S'utilise pour trouver les établissements les plus proches d'une position en donnant une limite
	 *
	 * float $latitude : la latitude de l'utilisateur
	 * float $longitude : la longitude de l'utilisateur
	 * int $offset : par où on commence à lire les résultats, à utiliser lors du lazy loading
	 * int $limit : le nombre d'établissements à afficher
	 *
	 **/
	public function getClosestBusinesses($latitude, $longitude, $offset = 0, $limit = 10) {

		$query = $this->_em->createQuery('
			SELECT b, 
			GEO_DISTANCE(:latitude, :longitude, b.latitude, b.longitude) AS distance 
			FROM BeerToBeerCoreBundle:Business b
			ORDER BY distance')
			->setParameter('latitude', $latitude)
		    ->setParameter('longitude', $longitude)
			->setFirstResult($offset)
			->setMaxResults($limit);

		$results =  $query->getArrayResult();

		// Render the results as the API wants it
		$businessesForApi = array();
		$i = 0;
		foreach ($results as $key => $result) {
			$businessesForApi[$i] = $result[0];
			$businessesForApi[$i]["distance"] = round($result["distance"]*1000, -1); // On ajoute la distance en mètres arrondi aux dizaines
			$i++;
		}

		return $businessesForApi;
	}
}
